const getItemListSql = `SELECT  
ROW_NUMBER() OVER (ORDER BY ST.STOK_KODU) AS id,
ST.STOK_KODU AS itemCode,
dbo.TRK(ST.STOK_ADI) AS itemName,
ST.OLCU_BR1 AS unitName,
ST.SATIS_FIAT1 as price1,
STE.KULL4S,
(SELECT SATIS_FIAT1 * 4 FROM TBLSTSABIT(NOLOCK) WHERE STOK_KODU=STE.KULL4S) AS accessoryExtra
FROM TBLSTSABIT ST 
LEFT JOIN TBLSTSABITEK STE ON ST.STOK_KODU=STE.STOK_KODU
 WHERE GRUP_KODU=@group`;

module.exports = { getItemListSql };
